export const pricingList = [
  {
    title: 'personal',
    price: 13,
    include: 'per month',
    annual: 156,
    includes: [
      'Send documents for eSignature: 5/month',
      'Single user only',
      'Integrates with Dropbox, Google Drive, and more.',
      'Real-time audit trail',
      'Top-rated mobile app',
      'Automate reminders & notifications',
      'Reusable templates',
    ],
  },
  {
    title: 'standard',
    price: 35,
    include: 'per user, per month',
    annual: 420,
    includes: [
      'Send documents for eSignature',
      'Buy up to 50 users online. For more than 50 users, Contact Sales',
      'Integrates with Dropbox, Google Drive, and more.',
      'Real-time audit trail',
      'Top-rated mobile app',
      'Automate reminders & notifications',
      'Reusable templates',
      'Shared documents',
      'Comments',
      'Shared templates',
      'Team reports',
      'In-person eSignatures',
      'Customized branding',
    ],
  },
  {
    title: 'business Pro',
    price: 55,
    include: 'per user, per month',
    annual: 660,
    includes: [
      'Send documents for eSignature',
      'Buy up to 50 users online. For more than 50 users, Contact Sales',
      'Integrates with Dropbox, Google Drive, and more.',
      'Real-time audit trail',
      'Top-rated mobile app',
      'Automate reminders & notifications',
      'Reusable templates',
      'Shared documents',
      'Comments',
      'Shared templates',
      'Team reports',
      'In-person eSignatures',
      'Customized branding',
      'Signer attachments',
      'Collaborative fields',
      'Advanced fields',
      'Drawing fields',
      'SMS authentication ($)',
      'PowerForms',
      'Collect Payments',
      'Bulk Send',
    ],
  },
];
