export const NavigatorRoute = {
  HOME: 'home',
  LOGIN: 'login',
  FORGOT_PASSWORD: 'forgot-password',
  TEST_API: 'test-api-server',
  TEST_COMPONENT: 'test_component',
  SLIDE: 'slide',
  FILE_PICKER: 'file_picker',
  SAMPLE_UI: {
    LANDING: 'landing',
    SAMPLE_DETAIL: 'sample_detail',
  },
  MODAL: 'modal',
  REGISTER: 'register',
  LOGIN2: 'login2',
  PRICING: 'pricing',
  HOME_WEB: 'home_web',
  HOME_MOBILE: 'home_mobile',
  TESTING_PAGE: 'testing_page',
  VIEW_UPLOAD: 'view_upload',
};
